### ISSUE TITLE
PdfQuery - newbee -I need some explications sorry if it is not here to do this, I don't find

### ISSUE THREAD

**Issue by pibol** [jcushman/pdfquery#19]
Hello Jcushman,
I read many pdf's texts. I don't do annotations popup but I only highlight text in yellow. I wanted to extract (with Python/ pdfMiner /pdfquery) this highlighted  text to do some indexation with Whoosh for my studies. I saw that when the text is highlihted the object created in the PDF's file is for example: 

20 0 obj
<<
/C [1 1 0]
/F 4
/M (D:20141107203743+01'00')
/P 7 0 R
/T (pibol)
/AP <<
/N 31 0 R
/NM (38048b89-6e9f-4434-9cae2b25dfc8c8a2)
/Rect [112.707338 807.385499 164.672639 816.770264]
/Subj (Surligner)
/Subtype /Highlight
/QuadPoints [114.570002 816.770274 162.809979 816.770274 114.570002
807.385508 162.809979 807.385508]
/CreationDate (D:20141107203743+01'00')
endobj`<<

Unlike a classical annotations popup here there is not the key " /Contents" and it is my problem. I have tried pdfMiner, pyPDF, PyPDF2  and  now pdfQuery but but ... I am not very good pythoner  and don't find the way to extract the line I want.

I have 2 questions :
Question 1 -  With pdfQuery I have tried this :

```
pdf = pdfquery.PDFQuery("c:\\myDocument.pdf")
pdf.load()
label = pdf.pq('LTTextLineHorizontal:contains("the line I want")')
print label
```

that gives me this :

```
<LTTextLineHorizontal bbox="[53.999, 313.813, 189.746, 324.91]" height="11.098" width="135.747" 
word_margin="0.1" x0="53.999" x1="189.746" y0="313.813" y1="324.91"><LTTextBoxHorizontal   
bbox="[53.999, 313.813, 189.746, 324.91]" height="11.098" index="10" width="135.747" 
x0="53.999" x1="189.746" y0="313.813" y1="324.91">the line I want </LTTextBoxHorizontal
</LTTextLineHorizontal>
```

With this I have the coordonates of my text with <LTTextLineHorizontal bbox.... 
To test this coordonates I wanted to recuperate the text  and only the text with  the order  ('with_formatter', 'text')  explains in your help but how ? I don't understand the way to do this : 

```
pdf.extract([('titleParagraf', ':in_bbox("53.999, 313.813, 189.746, 324.91")',('with_formatter', 'text')) ]) ??
```

Question 2 :  Is it possible with pdfQuery to find one highlihted text in yellow in a text and recuperate this coordonates to extract the text with pdf.extract(['aaaa',':inbbox(coordonatesOf theHighlitedText)]).

I hope don't be too boring and quite clear in my explanations. English it is not my prefered language.
Thanks for your patience and sorry if it was not here to request some help.

Pibol

**Comment by Adithiyanjithu** [comment]
How can i fetch annot tag value
