### ISSUE TITLE
Please help with API usage

### ISSUE THREAD

**Issue by swasher** [jcushman/pdfquery#21]
First, thanks you for great library. 
My question is how I can extract text if I know 'figure' name. For example, I need extract text from XObject named **pssMO3_1**. I can make xml file with command like `pdf.tree.write(fxml, pretty_print=True, encoding="utf-8")`, and this file will contain all needed data under **figure name="pssMO3_1"** tag: 

    $ cat out.xml 
    <?xml version="1.0" encoding="utf-8" ?>
    <pages>
    <page id="1" bbox="0.000,0.000,2097.638,1629.921" rotate="0">
    <figure name="pssMO3_1" bbox="1939.906,240.945,1955.906,445.945">
    <text font="JDMBFC+ArialUnicodeMS" bbox="1941.468,245.945,1952.732,251.281" size="5.336">B</text>
    <text font="JDMBFC+ArialUnicodeMS" bbox="1941.468,251.281,1952.732,253.057" size="1.776">l</text>
    <text font="JDMBFC+ArialUnicodeMS" bbox="1941.468,253.057,1952.732,257.505" size="4.448">a</text>
    <text font="JDMBFC+ArialUnicodeMS" bbox="1941.468,257.505,1952.732,261.505" size="4.000">c</text>
    <text font="JDMBFC+ArialUnicodeMS" bbox="1941.468,261.505,1952.732,265.505" size="4.000">k</text>
    and so on...

How I can extract text ('Black ...') using library API?
Thanks in advance!

**Comment by jcushman** [comment]
Hi, swasher.

In this case, try something like `pdf.pq('figure[name="pssMO3_1"]').text()`.

In general, you can use `pdf.pq()` just like jQuery's `$()` to extract elements you want, and then `.text()` to get their text contents. If you haven't worked with jQuery before, reading up on that is the place to start -- check out http://learn.jquery.com/using-jquery-core/selecting-elements/
