### ISSUE TITLE
Documentation on caching

### ISSUE THREAD

**Issue by twsh** [jcushman/pdfquery#25]
I think there's a small mistake in the documentation for caching: FileCache is imported as 'FileCache' but called as 'pdfquery.FileCache'. This is works for me:

```
from pdfquery.cache import FileCache
pdfquery.PDFQuery("tests/samples/IRS_1040A.pdf", parse_tree_cacher=FileCache("/tmp/"))
```
(It also seems to be formatted differently from the other examples.)

**Comment by jcushman** [comment]
Thanks!
