### ISSUE TITLE
Where'd my links go? 

### ISSUE THREAD

**Issue by mlissner** [jcushman/pdfquery#28]
I'm trying to query the links in a document on a court website, but when I look at the XML, the links seem to be gone. 

For example, the document I'm working with is here:

http://apps.courts.ky.gov/supreme/casesummaries/May2015.pdf

Not far down that PDF there's a link to:

http://opinions.kycourts.net/sc/2013-SC-000610-MR.pdf

But if I look at the XML (generated with `pdf.tree.write('ky.xml', pretty_print=True, encoding='utf-8')`), there doesn't seem to be any links. I've posted the XML here:

https://gist.github.com/mlissner/4cb1eb36e347c2dea00a

Any ideas, or is this something pdfquery doesn't support?

Thanks! It's been interesting playing with this.

cc: @brianwc

**Comment by jcushman** [comment]
Unfortunately the links don't make it into the generated XML right now, but they do show up in the PDFMiner annotations for a given page, so you can grab them from there. `pdf.get_page` will give you the PDFMiner `PDFPage` object:

```
>>> first_page = pdf.get_page(0)
>>> first_page.annots
[<PDFObjRef:13>, <PDFObjRef:21>]
>>> first_page.annots[0].resolve()
{'A': {'S': /URI,
  'Type': /Action,
  'URI': 'http://opinions.kycourts.net/sc/2013-SC-000610-MR.pdf'},
 'BS': {'W': 0},
 'F': 4,
 'Rect': [123.75, 609.61, 235.57, 623.41],
 'StructParent': 1,
 'Subtype': /Link}
```

Ideally these annotations should be included in the generated XML and queryable like text elements, but they aren't currently.

(For future reference, here's another example of grabbing stuff from annotations: https://github.com/10layer/PDF-Mine/blob/master/pdfmine.py#L156)

**Comment by mlissner** [comment]
Thanks for the reply. So, seems like we need the `load` function to also iterate over the pages, calling `pdf.get_page` for each and then putting the important parts of that into the generated XML. I've only glanced at the code, but that doesn't seem terribly hard. 

The sample in `PDF-Mine` for pulling out links looks like a good starting place.

My first thought on how this should work is to put a node in the XML for each page that has all the links in a document. Something like:

    <pdfxml bunch-of-attributes="foo">
        <LTPage bunch-more-attributes="bar">
            <a bboxx="[123.75, 609.61, 235.57, 623.41]" uri="https://example.com"/>
            <a bboxx="[some, other, bbox, here]" uri="https://example2.com"/>
            <a bboxx="[some, other, bbox, here]" uri="https://example3.com"/>
            <LTTextLineHorizontal>
                <SO-MUCH-JUNK/>
            </LTTextLineHorizontal>
        </LTPage>
        ...more pages here...
    </pdfxml>

Possible tweaks:

 - uri or href? 
 - <A> or <a>?
 - Inclusion of any of the other details from the `annots` resolution in your previous comment? 
 - Do we include bookmarks or only links?

**Comment by jcushman** [comment]
How about this? This is basically a simple dump of the `annots` dict into the XML (from the first page in your example PDF):

```
<pdfxml ...>
  <LTPage ...>
    <LTTextLineHorizontal ...>...</LTTextLineHorizontal>
    <LTTextLineHorizontal ...>...</LTTextLineHorizontal>
    <LTTextLineHorizontal ...>...</LTTextLineHorizontal>
    ...
    <Annot A="{u'S': u'/URI', u'Type': u'/Action', u'URI': u'http://opinions.kycourts.net/sc/2012-SC-000694-DG.pdf'}" BS="{u'W': 0}" F="4" StructParent="4" Subtype="/Link" URI="http://opinions.kycourts.net/sc/2012-SC-000694-DG.pdf" bbox="[123.75, 678.6, 233.58, 692.4]" height="13.8" width="109.83" x0="123.75" x1="233.58" y0="678.6" y1="692.4"/>
    <Annot A="{u'S': u'/URI', u'Type': u'/Action', u'URI': u'http://opinions.kycourts.net/sc/2011-SC-000737-DG.pdf'}" BS="{u'W': 0}" F="4" StructParent="5" Subtype="/Link" URI="http://opinions.kycourts.net/sc/2011-SC-000737-DG.pdf" bbox="[123.75, 361.23, 233.58, 375.03]" height="13.8" width="109.83" x0="123.75" x1="233.58" y0="361.23" y1="375.03"/>
    <Annot A="{u'S': u'/URI', u'Type': u'/Action', u'URI': u'http://opinions.kycourts.net/sc/2012-SC-000599-DG.pdf'}" BS="{u'W': 0}" F="4" StructParent="6" Subtype="/Link" URI="http://opinions.kycourts.net/sc/2012-SC-000599-DG.pdf" bbox="[123.75, 347.43, 233.58, 361.23]" height="13.8" width="109.83" x0="123.75" x1="233.58" y0="347.43" y1="361.23"/>
  </LTPage>
</pdfxml>
```

I'm just modifying the `annots` dict to change `Rect` to `bbox`, insert `width/height/x0/x1/y0/y1`, and pull out `['A']['URI']` as its own attribute for easier searching. Messy, but hopefully this'll make it possible for people to get what they want for any annotation type.

(Of which there are apparently many -- see page 389 et seq. of the spec: http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf)

Note: in this approach you should *not* assume that `Annot` elements will be directly under `LTPage` -- if they fit within a sub-element bbox-wise they'll hopefully-maybe be sorted into there.

**Comment by mlissner** [comment]
OK, I think I sent a pretty good PR for this. It was a fair bit to wrap my head around, but I think the solution I sent is pretty good. All tests pass, and it adds the <annot> elements as described above. A few caveats are in the commit messages.

Let me know what you think!

**Comment by jcushman** [comment]
Version 0.3.0 is pushed to pypi with support for annotations. Thanks for your help on this.

**Comment by mlissner** [comment]
Fantastic! My pleasure. Thanks for the quick reviews!
