### ISSUE TITLE
Text in PDF has an extra LTTextBoxHorizontal whereas similar text elsewhere doesn't

### ISSUE THREAD

**Issue by sreejithr** [jcushman/pdfquery#34]
Here's the deal. I did this on a PDF:
```
pdf.extract([
  ('with_parent', 'LTPage[pageid="1"]'),
  ('name', 'LTTextLineHorizontal:contains("24x7 claims assistance")')
])
```
I got a `[<LTTextLineHorizontal>]`. Let's say I assign it to a variable `result`. Then,

```
In [61]: result
Out[61]: [<LTTextLineHorizontal>]

In [62]: result[0]
Out[62]: <Element LTTextLineHorizontal at 0x10dc621b0>

In [63]: result[0][0]
Out[63]: <Element LTTextBoxHorizontal at 0x10dc62158>
```
In the same PDF, I do this:
```
pdf.extract([
  ('with_parent', 'LTPage[pageid="1"]'),
  ('name', 'LTTextLineHorizontal:contains("9810510983")')
])
```
Again I got a `[<LTTextLineHorizontal>]`. Then,

```
In [70]: result
Out[61]: [<LTTextLineHorizontal>]

In [71]: result[0]
Out[62]: <Element LTTextLineHorizontal at 0x10dc621b0>

In [72]: result[0][0]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-64-223da891ff7c> in <module>()
----> 1 result[0][0]

lxml.etree.pyx in lxml.etree._Element.__getitem__ (src/lxml/lxml.etree.c:47744)()

IndexError: list index out of range
```
I went through the code. I see that you're using `_clean_text()` in `pdfquery.py` to keep the text value in the leaf node and erase the value out of its parents.

I'm sorry but I couldn't enough time to debug it fully. Does anyone know why this would happen?

**Comment by sreejithr** [comment]
About sharing the PDF, I'll need to talk to my employer. Thanks in advance :)

**Comment by jcushman** [comment]
`[<LTTextLineHorizontal>]` is a pyquery result set, not a list, so it has a method `result.text()` that will return the text contents in either example -- assuming that's what you're looking for. You can also add `('with_formatter', 'text')` to have that applied to all your results, as in the examples from the docs.

If you want to understand the structure you're getting back in general, `pdf.tree.write(filename, pretty_print=True)` is a good place to start.
