### ISSUE TITLE
Large Memory Usage

### ISSUE THREAD

**Issue by jtsmith2** [jcushman/pdfquery#50]
I have a very large PDF (about 1000  pages).  Since I didn't think it would be wise to load the entire PDF into memory at the same time, I decided to iterate over the pages, calling pdf.load on each page individually thinking this would only load one page in at a time.  However, it seems that memory usage continues to grow every time pdf.load is called, like the previous data is not being released.  Any ideas?  I'm running out of memory (16GB) after about 400 pages.

**Comment by jcushman** [comment]
`load` doesn't throw away previous results if you call it multiple times. If you do:

```
pdf = PDFQuery("example.pdf")
pdf.load(1)
pdf.load(2)
```

then you have both pages 1 and 2 loaded, and memory will increase. Meanwhile this should hopefully have flat memory use and perform almost as quickly:

```
pdf = PDFQuery("example.pdf")
pdf.load(1)
pdf = PDFQuery("example.pdf")
pdf.load(2)
```

If memory use increases with the second example, feel free to reopen.
