### ISSUE TITLE
chardet 3.0 seems to have broken something

### ISSUE THREAD

**Issue by ses4j** [jcushman/pdfquery#54]
In pdfquery.py, in `smart_unicode_decode` is this:

    # detect encoding
    detected_encoding = chardet.detect(encoded_string)

With chardet 2.3.0, `detected_encoding` is `{'confidence': 0.0, 'encoding': None}`

With chardet 3.0.1 (newest as of time of writing this), `detected_encoding` is `None`

So it's crashing on the next line, where it does `detected_encoding['encoding']`.

Presumably, the fix is as simply as changing:

`encoding=detected_encoding['encoding'] or 'utf8',`

to

`encoding=detected_encoding['encoding'] if (detected_encoding and detected_encoding['encoding']) else 'utf8',`

**Comment by ses4j** [comment]
Workaround for now is simply to force the old one in requirements.txt:

    pdfquery
    chardet~=2.3

**Comment by jcushman** [comment]
Thanks!
