### ISSUE TITLE
pdf query not catching some text in page

### ISSUE THREAD

**Issue by mayur62662** [jcushman/pdfquery#55]
I am using the following code

tax = pdf.pq('LTTextLineHorizontal:in_bbox("%s, %s, %s, %s")' % (
                    col['tax']['start'], line, col['tax']['end'], line+10)).text()

where i am expecting to catch text something like '8 G1' or '32 G1'
here it catches value '32 G1' but not '8 G1' 
actually any single digit value is not caught here.
'589 TKTT 1253925356 14APR17 FVVV D CA 4,440 3,425 **8 G1** 450 YQ
75 YR 3,386 1.01 39 0.00'
 above what my line in pdf line is.
it is catching values at that posssition before and after but not here and in situations like this one.
please help with it
Mayuresh A

**Comment by jcushman** [comment]
Hi! I can't really debug this for you. My general suggestion is to try `pdf.tree.write("tree.xml", pretty_print=True)` and see why the element you're looking for doesn't match your selector.
