### ISSUE TITLE
438 page PDF takes ~700 sec and ~4GB RAM to load

### ISSUE THREAD

**Issue by dsvensson** [jcushman/pdfquery#57]
http://www.atmel.com/Images/Atmel-7766-8-bit-AVR-ATmega16U4-32U4_Datasheet.pdf

During these 700 seconds, only one core is working on 100%, would it be possible to cut the work in 8 in my case by letting the rest of the cores in on the fun?

Is this expected load time? This is using a Intel Core i7-7700K 4 cores with HT => 8 threads, 16GB ram, macOS Sierra, Python 3.6.

However.. using FileCache brings down subsequent runs to 0.8 seconds load time.

Perhaps you could provide some expected performance metrics in the README to quantify _"runs very slowly"_?
```
pdf = pdfquery.PDFQuery(args.datasheet, parse_tree_cacher=FileCache("/tmp/"))
t0 = time.time()
pdf.load()
t1 = time.time()

print("Loaded in {} seconds".format(t1-t0))
```

**Comment by jcushman** [comment]
Hi! There aren't really any predictable performance metrics -- what's happening here is that the PDFMiner library we use to get page layouts is running some sort of inefficient algorithm to sort all the elements on each page of the PDF, so if you have pages with a lot of elements on them it will increase processing time exponentially.

The way to fix this would be to implement a more efficient algorithm inside PDFMiner's `process_page` function -- https://github.com/pdfminer/pdfminer.six/blob/master/pdfminer/pdfinterp.py#L840

In the meantime you could definitely write a program with `multiprocessing` that calls `pdf.load(n)` for each page in 8 processes.
