### ISSUE TITLE
Custom selectors don't support partial functions 

### ISSUE THREAD

**Issue by draperjames** [jcushman/pdfquery#60]
From my [SO question](https://stackoverflow.com/questions/45868809/attribute-error-when-using-functools-partial-in-pdfquery-filter) on the same issue.

# Background

I'm using pdfquery to parse multiple files like [this one](https://assets.thermofisher.com/TFS-Assets/LSG/certificate/Certificates%20of%20Analysis/RG234621_90110.pdf).

# Problem
I'm trying to write a generalized filer function, building off of the custom selectors mentioned in [pdfquery's docs](https://github.com/jcushman/pdfquery#custom-selectors), that can take a specific range as an argument. Because `this` is referenced I thought I could get around this by supplying a partial function using `functools.partial` (as seen below)

## Input

    import pdfquery
    import functools
    
    def load_file(PDF_FILE):
        pdf = pdfquery.PDFQuery(PDF_FILE)
        pdf.load()
        return pdf

    file_with_table = 'Path to the file mentioned above'
    pdf = load_file(file_with_table)
    
    
    def elements_in_range(x1_range):
        return in_range(x1_range[0], x1_range[1], float(this.get('x1',0)))
    
    x1_part = functools.partial(elements_in_range, (95,350))
    
    pdf.pq('LTPage[page_index="0"] *').filter(x1_part)

But when I do that I get the following attribute error;

## Output

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    C:\Anaconda3\lib\site-packages\pyquery\pyquery.py in filter(self, selector)
        597                     if len(args) == 1:
    --> 598                         func_globals(selector)['this'] = this
        599                     if callback(selector, i, this):
    
    C:\Anaconda3\lib\site-packages\pyquery\pyquery.py in func_globals(f)
         28 def func_globals(f):
    ---> 29     return f.__globals__ if PY3k else f.func_globals
         30 
    
    AttributeError: 'functools.partial' object has no attribute '__globals__'
    
    During handling of the above exception, another exception occurred:
    
    AttributeError                            Traceback (most recent call last)
    <ipython-input-74-d75c2c19f74b> in <module>()
         15 x1_part = functools.partial(elements_in_range, (95,350))
         16 
    ---> 17 pdf.pq('LTPage[page_index="0"] *').filter(x1_part)
    
    C:\Anaconda3\lib\site-packages\pyquery\pyquery.py in filter(self, selector)
        600                         elements.append(this)
        601             finally:
    --> 602                 f_globals = func_globals(selector)
        603                 if 'this' in f_globals:
        604                     del f_globals['this']
    
    C:\Anaconda3\lib\site-packages\pyquery\pyquery.py in func_globals(f)
         27 
         28 def func_globals(f):
    ---> 29     return f.__globals__ if PY3k else f.func_globals
         30 
         31 
    
    AttributeError: 'functools.partial' object has no attribute '__globals__'

Is there any way to get around this? Or possibly some other way to write a custom selector for pdfquery that can take arguments?

@jcushman 
If this is module level problem how difficult would it be to fix?

Other than that I'm really enjoying pdfquery. Thanks!

**Comment by jcushman** [comment]
Sorry for late reply -- looks like you found an answer on SO.

For future reference, this question relates to standard use of [pyquery](https://github.com/gawel/pyquery/)'s `filter` method, nothing special to pdfquery, so that's a good place to look for help or file issues.

I can't resist commenting on the actual question, even though I'm sure it's too late to be helpful. :) I think what's happening here is pyquery's magic to inject `this` is interfering with the magic behind `functools.partial`. So I would remove both kinds of magic, and just use standard lambda functions and pass around `this` explicitly:

```
  def elements_in_range(a, b, this):
    return in_range(a, b, float(this.get('x1',0)))

  x1_part = lambda: elements_in_range(95, 350, this)
```
